api_platform:
    title: 'Symfony Modular API'
    version: '1.0.0'
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        pagination_client_enabled: true
        pagination_client_items_per_page: true
    collection:
        pagination:
            enabled: true
            items_per_page: 30
            items_per_page_parameter_name: itemsPerPage
            maximum_items_per_page: 100
    mapping:
        paths: ['%kernel.project_dir%/src/Modules/*/Entity']
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
