doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: 'pdo_mysql'
        server_version: '8.0'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
    
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            User:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/User/Entity'
                prefix: 'Modules\User\Entity'
                alias: User
            Business:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/Business/Entity'
                prefix: 'Modules\Business\Entity'
                alias: Business
            Core:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/Core/Entity'
                prefix: 'Modules\Core\Entity'
                alias: Core
            Analytics:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/Analytics/Entity'
                prefix: 'Modules\Analytics\Entity'
                alias: Analytics
            Notification:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Modules/Notification/Entity'
                prefix: 'Modules\Notification\Entity'
                alias: Notification

