framework:
    http_method_override: false
    handle_all_throwables: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    php_errors:
        log: true
    profiler:
        only_exceptions: false
    router:
        default_uri: http://localhost
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    http_client:
        scoped_clients:
            # configure a scoped HTTP client for the API
            api_client:
                base_uri: 'https://api.github.com/'
                headers:
                    Accept: 'application/vnd.github.v3+json'
                    User-Agent: 'MyApp/1.0'
            # an HTTP client scoped to the local API
            local_api_client:
                base_uri: 'http://localhost/api/'
    mailer:
        dsn: '%env(MAILER_DSN)%'
    cache:
        app: cache.adapter.redis
        default_redis_provider: redis://redis:6379
    serializer:
        enable_annotations: true
        mapping:
            paths: ['%kernel.project_dir%/config/serialization']
