# Configuration de l'assistant d'installation
installation:
    # Titre de l'application
    app_name: 'Application Symfony'
    app_version: '1.0.0'
    
    # Configuration de la base de données
    database:
        default_host: 'localhost'
        default_port: 3306
        default_name: 'symfony_app'
        default_user: 'symfony_user'
        required_extensions: ['pdo_mysql']
    
    # Configuration des mots de passe
    password:
        min_length: 8
        require_uppercase: true
        require_lowercase: true
        require_numbers: true
        require_special_chars: true
    
    # Vérifications système
    system_checks:
        php_version: '8.1.0'
        required_extensions: ['pdo_mysql', 'mbstring', 'xml', 'curl', 'zip']
        required_directories: ['var', 'var/cache', 'var/logs', 'public/uploads']
        required_files: ['.env']
    
    # Configuration des dossiers
    directories:
        var: 0755
        var_cache: 0755
        var_logs: 0755
        public_uploads: 0755
        config_jwt: 0755
    
    # Configuration des fichiers
    files:
        env: 0644
        install_lock: 0644
    
    # Messages personnalisés
    messages:
        welcome: 'Bienvenue dans l\'assistant d\'installation'
        system_check: 'Vérification des prérequis système'
        database_config: 'Configuration de la base de données'
        admin_creation: 'Création du compte administrateur'
        finalization: 'Finalisation de l\'installation'
        success: 'Installation terminée avec succès !'
        error: 'Une erreur est survenue'
    
    # Configuration de sécurité
    security:
        max_attempts: 3
        lockout_duration: 300
        session_timeout: 1800
    
    # Configuration de l'interface
    ui:
        theme: 'default'
        language: 'fr'
        show_progress: true
        enable_animations: true
