framework:
    messenger:
        default_bus: messenger.bus.default
        buses:
            messenger.bus.default: ~
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
        routing:
            'Modules\Core\Message\AsyncMessage': async
            'Modules\Core\Message\EmailMessage': async
            'Modules\Notification\Message\NotificationMessage': async
