framework:
    messenger:
        default_bus: messenger.bus.default
        buses:
            messenger.bus.default: ~
        transports:
            async: 'sync://'
            failed: 'doctrine://default?queue_name=failed'
        routing:
            # Temporairement désactivé car les modules ne sont pas chargés
            # 'Modules\Core\Message\AsyncMessage': async
            # 'Modules\Core\Message\EmailMessage': async
            # 'Modules\Notification\Message\NotificationMessage': async
