# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    kernel.secret: '%env(APP_SECRET)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Command/InitGlobalConfigCommand.php'
            - '../src/Migrations/'
            - '../src/Modules/'
    
    # Modules
    Modules\:
        resource: '../src/Modules/'
        exclude:
            - '../src/Modules/*/Entity/'
            - '../src/Modules/*/Repository/'
            - '../src/Modules/*/AnalyticsBundle.php'
            - '../src/Modules/*/ApiBundle.php'
            - '../src/Modules/*/BusinessBundle.php'
            - '../src/Modules/*/CoreBundle.php'
            - '../src/Modules/*/NotificationBundle.php'
            - '../src/Modules/*/UserBundle.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Installation services
    App\Service\InstallationService:
        autowire: true

    App\EventListener\InstallationListener:
        tags:
            - { name: kernel.event_subscriber }

    # Commands
    App\Command\ResetInstallationCommand:
        autowire: true
        tags:
            - { name: console.command }
    
    # Temporarily disabled due to module loading issues
    # App\Command\InitGlobalConfigCommand:
    #     tags:
    #         - { name: console.command }
